name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main  # 指定触发 action 的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      # 安装依赖
    - name: install
      run: npm i
      # 打包构建
    - name: build
      run: npm run build
      # 部署运行
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
